name: GitHub Action
run-name: Test action
on: [push]
jobs:
  test-action:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.1.1
        with:
          issue-number: 5
          body: |
            Test comment
          reactions: 'rocket'
