name: Review app teardown pipeline

concurrency:
  group: review-${{ github.event.pull_request.number }}

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  infra:
    name: Teardown review app - TODO
    environment: review
