name: Staging CI/CD Pipeline

on:
  push:
    branches:
      - main
      - prod-pipeline-testing
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  aws_deploy:
    name: AWS Deploy
    if: github.ref == 'refs/heads/prod-pipeline-testing'
    # needs: [lint, test, feature_test, audit]
    uses: ./.github/workflows/aws_deploy.yml
    with:
      aws_account_id: 107155005276
      aws_resource_prefix: core-staging
      environment: staging
    permissions:
      id-token: write
