name: Staging CI/CD Pipeline

on:
  push:
    branches:
      - cldc-2563-aws-production-pipeline
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  aws_deploy:
    name: AWS Deploy
    if: github.ref == 'refs/heads/cldc-2563-aws-production-pipeline'
    # needs: [lint, test, feature_test, audit]
    uses: ./.github/workflows/aws_deploy.yml
    with:
      aws_account_id: 977287343304
      aws_resource_prefix: core-prod
      environment: production
    permissions:
      id-token: write
